spring:
  batch:
    job:
      enabled: false
  data:
      elasticsearch:
        clusterName: adm-cluster
        clusterNodes: localhost:9300
        #local: true
        properties:
          http:
            enabled: true
        repositories:
          enabled: true

mysql:
  password: mypass
  user: jeffrey
  host: localhost
  port: 3306
  dbName: db_issue1